// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const.java
// Do not modify

package org.projectfloodlight.openflow.protocol;


public enum OFBadInstructionCode {
     UNKNOWN_INST,
     UNSUP_INST,
     BAD_TABLE_ID,
     UNSUP_METADATA,
     UNSUP_METADATA_MASK,
     UNSUP_EXP_INST,
     BAD_EXPERIMENTER,
     BAD_EXPERIMENTER_TYPE,
     BAD_LEN,
     EPERM;
}
