// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const.java
// Do not modify

package org.projectfloodlight.openflow.protocol;


public enum OFBadActionCode {
     BAD_TYPE,
     BAD_LEN,
     BAD_EXPERIMENTER,
     BAD_EXPERIMENTER_TYPE,
     BAD_OUT_PORT,
     BAD_ARGUMENT,
     EPERM,
     TOO_MANY,
     BAD_QUEUE,
     BAD_OUT_GROUP,
     MATCH_INCONSISTENT,
     UNSUPPORTED_ORDER,
     BAD_TAG,
     BAD_SET_TYPE,
     BAD_SET_LEN,
     BAD_SET_ARGUMENT;
}
