// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const.java
// Do not modify

package org.projectfloodlight.openflow.protocol;

import org.projectfloodlight.openflow.protocol.actionid.*;

public enum OFErrorType {
     HELLO_FAILED,
     BAD_REQUEST,
     BAD_ACTION,
     FLOW_MOD_FAILED,
     PORT_MOD_FAILED,
     QUEUE_OP_FAILED,
     BAD_INSTRUCTION,
     BAD_MATCH,
     GROUP_MOD_FAILED,
     TABLE_MOD_FAILED,
     SWITCH_CONFIG_FAILED,
     ROLE_REQUEST_FAILED,
     EXPERIMENTER,
     METER_MOD_FAILED,
     TABLE_FEATURES_FAILED;
}
